#!/usr/bin/env bash
# Configures Nginx to listen on port 80, serves a page, and ensures it's not running afterward
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx start
curl -s -o /dev/null -w "%{http_code}" 0:80
service nginx stop
